README.md
nodejs/basic-bot/README.md
nodejs/basic-bot/index.js
nodejs/basic-bot/package.json

This project includes basic NodeJS sample. Undergoing the other few features like Cards and Auth will do soon.

Includes Nodejs

---

python/productivity_tracker/readme.md

Fixing the `readme.md`'s instructions.

adjusting git url and pathing

---

python/productivity_tracker/.gcloudignore
python/productivity_tracker/app.yaml
python/productivity_tracker/productivity_bot/api_helper.py
python/productivity_tracker/productivity_bot/inbound_message_handlers.py
python/productivity_tracker/productivity_bot/message_users_helpers.py
python/productivity_tracker/productivity_bot/nlp_helper.py
python/productivity_tracker/productivity_bot/views.py
python/productivity_tracker/readme.md
python/productivity_tracker/requirements.txt

Update to python 3 and all dependencies. Some minor delinting of code as well.
Sample still needs a bit more work if we want to keep it. Instructions are woefully inadequate and there are a lot of rough edges when using it.

Update productivity tracker to python 3

---

node/webhook/index.js

Hangout Chat
Webhook(Bug_id-232891039) : Sends asynchronous message into Google Chat.

Hangout Chat : Webhook

---

python/webhook/quickstart.py

A quickstart script for using an incoming webhook for Hangouts chat room samples.
Fixes # (issue)

Incoming webhook for Hangouts chat samples in Python

---

java/avatar-bot/README.md
java/avatar-bot/pom.xml
java/avatar-bot/src/main/java/HelloChat.java

Java Code Sample to build Avatar Bot using Google Cloud Functions
See [instructions](https://developers.google.com/hangouts/chat/quickstart/gcf-bot).

feat: Java Avatar Bot

---

apps-script/webhook/README.md
apps-script/webhook/webhook.gs

Apps Script Webhook sample to send messages to Google Chat
[Instructions](https://developers.google.com/chat/how-tos/webhooks)

feat: Apps Script Webhook sample

---

java/avatar-bot/pom.xml
java/webhook/README.md
java/webhook/pom.xml
java/webhook/src/main/java/com/google/hangouts/chat/webhook/App.java

Java Webhook sample to send messages to Google Chat
[Instructions](https://developers.google.com/chat/how-tos/webhooks)

feat: Java Webhook sample

---

python/auth-bot/.gcloudignore
python/auth-bot/README.md
python/auth-bot/app.yaml
python/auth-bot/auth.py
python/auth-bot/main.py

- Add typing
- Add license definitions
- Update `app.yaml`
- Update `README.md` to new Python 3 virtual enviroment style

Update for Python 3.10

---

python/card-bot/main.py

- Add 'match' statements in place of 'if/elif'.
- Add parameter typing to method calls.
- Change quote marks to be consistent

Update samples to Python 3.10

---

node/avatar-bot/index.js

Reference doc https://developers.google.com/chat/api/reference/rest/v1/cards

feat: Update Node avatar bot sample to use CardsV2

---

node/preview-link/attach-card.js
node/preview-link/preview-link.js
node/preview-link/sender-type.js
node/preview-link/simple-text-message.js
node/preview-link/update-card.js

Reference doc https://developers.google.com/chat/api/reference/rest/v1/cards

feat: Update Node preview link sample to use CardsV2

---

apps-script/preview-link/attach-card.gs
apps-script/preview-link/preview-link.gs
apps-script/preview-link/sender-type.gs
apps-script/preview-link/update-card.gs

Reference doc https://developers.google.com/chat/api/reference/rest/v1/cards

feat: Update Apps Script preview link sample to use CardsV2

---

java/avatar-bot/pom.xml
java/avatar-bot/src/main/java/HelloChat.java

* https://googleapis.dev/java/google-api-services-chat/latest/
* https://developers.google.com/chat/api/reference/rest/v1/cards

feat: Update Java avatar bot sample to use CardsV2

---

apps-script/avatar-bot/hello-chat.gs

Reference: https://developers.google.com/chat/api/reference/rest/v1/cards

feat: Update Apps Script avatar bot sample to use CardsV2

---

node/avatar-bot/index.js

Name needs to match instructions: https://developers.google.com/chat/quickstart/gcf-app#node.js

fix: Update Node Avatar Bot function name

---

node/.eslintrc.js
node/pagespeed-app/README.md
node/pagespeed-app/index.js
node/pagespeed-app/package-lock.json
node/pagespeed-app/package.json

A Google Chat app using [PageSpeed API](https://developers.google.com/speed/docs/insights/v5/get-started) to fetch URL speed insights.

feat: Node.js PageSpeed Chat App

---

python/avatar-bot/README.md
python/avatar-bot/main.py
python/avatar-bot/requirements.txt

- Add missing return typing to `main.py`
- Replace `Hangouts` and fix the quickstart URL
- Add `functions_framework` to the requirements.

Update and freshen the avatar-bot

---

python/basic-async-bot/README.md
python/basic-async-bot/app.yaml
python/basic-async-bot/main.py
python/basic-async-bot/requirements.txt

- Update `README.md` and `main.py` to replace references to 'Hangouts' with 'Google Chat'
- Update python version in app.yaml
- Update typing in `main.py`
- Update `requirements.txt` to use `>=` to ensure future library freshness

Update and freshen samples

---

python/pub-sub-bot/README.md
python/pub-sub-bot/bot.py
python/pub-sub-bot/requirements.txt

- Replace references to 'Hangouts Chat' with 'Google Chat'
- Update doc URLs
- Update code to Python 3.10

Update to Python 3.10

---

apps-script/selection-input/README.md
apps-script/selection-input/on-widget-update.gs

https://developers.google.com/chat/ui/widgets/selection-input#multiselect-menu

feat: Move Apps Script sample to Github

---

apps-script/incident-response/ChatApp.gs
apps-script/incident-response/ChatSpaceCreator.gs
apps-script/incident-response/appsscript.json

Updates the code for all the Chat API calls in the Incident Response Apps Script sample to use the new [advanced service](https://developers.google.com/apps-script/advanced/chat).

feat: Use Chat adv service in inc response sample

---

node/ai-knowledge-assistant/.gcloudignore
node/ai-knowledge-assistant/.gitignore
node/ai-knowledge-assistant/README.md
node/ai-knowledge-assistant/controllers/app.js
node/ai-knowledge-assistant/controllers/event-app.js
node/ai-knowledge-assistant/deploy.sh
node/ai-knowledge-assistant/env.js
node/ai-knowledge-assistant/events_index.js
node/ai-knowledge-assistant/http_index.js
node/ai-knowledge-assistant/index.js
node/ai-knowledge-assistant/model/events.js
node/ai-knowledge-assistant/model/exceptions.js
node/ai-knowledge-assistant/model/message.js
node/ai-knowledge-assistant/package-lock.json
node/ai-knowledge-assistant/package.json
node/ai-knowledge-assistant/services/aip-service.js
node/ai-knowledge-assistant/services/app-auth-chat-service.js
node/ai-knowledge-assistant/services/app-auth-events-service.js
node/ai-knowledge-assistant/services/firestore-service.js
node/ai-knowledge-assistant/services/user-auth-chat-service.js
node/ai-knowledge-assistant/services/user-auth-events-service.js
node/ai-knowledge-assistant/services/user-auth.js
node/ai-knowledge-assistant/test/events_index.test.js
node/ai-knowledge-assistant/test/http_index.test.js

Add AI knowledge assistant Node.js demo.

feat: Add AI knowledge assistant Node.js demo

---

java/basic-app/README.md
java/basic-app/pom.xml
java/basic-app/src/main/appengine/app.yaml
java/basic-app/src/main/java/com/google/chat/app/basic/App.java

* Upgraded Java to version 17 because Java 11 is deprecated in AppEngine
* Upgraded README fixing branding and links
* Added support for both project number and app URL verification methods
* Upgraded all dependencies to secure versions
* Upgraded code snippet region tags
* Fixed Google Code Style issues

feat: add request verification methods to basic app java

---

python/basic-app/README.md
python/basic-app/app.yaml
python/basic-app/main.py
python/basic-app/requirements.txt

- Upgraded Python to version 3.12 because Python 3.7 is deprecated in AppEngine
- Upgraded README fixing branding and links
- Added support for both project number and app URL verification methods
- Upgraded all dependencies to latest versions
- Upgraded code snippet region tags

feat: add request verification methods to basic app python

---

node/basic-app/.gcloudignore
node/basic-app/README.md
node/basic-app/app.yaml
node/basic-app/index.js
node/basic-app/package-lock.json
node/basic-app/package.json

- Upgraded to Google App Engine with Node.JS 20
- Upgraded README fixing branding and links
- Added support for both project number and app URL verification methods
- Upgraded all dependencies to secure versions
- Upgraded code snippet region tags

feat: add request verification methods to basic app node.js

---

node/pub-sub-app/README.md
node/pub-sub-app/index.js
node/pub-sub-app/package-lock.json
node/pub-sub-app/package.json

Based on the implementation in Python https://github.com/googleworkspace/google-chat-samples/pull/291.

feat: Add the pub-sub-app for Node.JS

---

java/pub-sub-app/README.md
python/pub-sub-app/README.md
python/pub-sub-app/app.py
python/pub-sub-app/requirements.txt

- Upgrade to GAPIC Chat client library
- Removed unnecessary requirements
- Use implementation from the existing PubSub quickstart guide in Java
- Mix some branding and indentation issues in README files

feat: Update the pub-sub-app for Python

---

java/app-home/README.md
java/app-home/pom.xml
java/app-home/src/main/appengine/app.yaml
java/app-home/src/main/java/com/google/chat/app/home/App.java
java/app-home/src/main/resources/applicaton.properties
node/app-home/.gcloudignore
node/app-home/README.md
node/app-home/app.yaml
node/app-home/index.js
node/app-home/package-lock.json
node/app-home/package.json
python/app-home/main.py

Also includes a typo fix in Python's implementation

feat: add app home code sample in Java and Node.js

---

apps-script/incident-response-app-auth/ChatApp.gs
apps-script/incident-response-app-auth/ChatSpaceCreator.gs
apps-script/incident-response-app-auth/Consts.gs
apps-script/incident-response-app-auth/DocsApi.gs
apps-script/incident-response-app-auth/Index.html
apps-script/incident-response-app-auth/JavaScript.html
apps-script/incident-response-app-auth/README.md
apps-script/incident-response-app-auth/Stylesheet.html
apps-script/incident-response-app-auth/VertexAiApi.gs
apps-script/incident-response-app-auth/WebController.gs
apps-script/incident-response-app-auth/appsscript.json

using app authentication model when using Chat API.
This App uses Chat API using app authentication.

feat: Add Apps Script Incident Response app sample

---

.github/workflows/publish.yml

See https://github.com/actions/runner-images/issues/11101 for more details.

fix: Upgrade Ubuntu to supported version
